project:
  type: website
  render:
    - "*.qmd"
  preview:
    port: 3333

execute:
  freeze: auto  # Re-render only when source changes

bibliography: files/bib/references.bib
csl: files/bib/chicago-author-date.csl

website:
  title: "WFLOAM 2024"
  description: "Actividad organizada por el proyecto de investigación MORA-DataS"
  site-url: "https://wflom.qrto.pub"

  favicon: "/files/icon-512.png"

  twitter-card:
    image: "/files/social-image-sp24.png"
    card-style: summary_large_image
    creator: "@andrewheiss"
    # site: "@andrewheiss"

  open-graph:
    image: "/files/social-image-sp24.png"
    locale: es_ES

  repo-actions: [edit, issue]

  page-navigation: true

  navbar:
    pinned: true
    background: "#EE6A24"
    right:
      - text: "Acerca de MORA-DataS"
        file: about/index.qmd
      - text: "Organización"
        file: organization/index.qmd
      - text: "Propuestas"
        file: submission/index.qmd
      - text: "Programa"
        file: program/index.qmd
      - text: "Registro"
        file: registration/index.qmd

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
    html-math-method: katex
